connectors:
  - port: 9890
    secure: true
    keyFilePath: key.pem
    certFilePath: cert.pem
  - port: 9889
harness-mongo:
  uri: mongodb://localhost:27017/harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

events-mongo:
  uri: mongodb://localhost:27017/events
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

secretsConfiguration:
  secretResolutionEnabled: false
  gcpSecretManagerProject: ccm-play

batchQueryConfig:
  queryBatchSize: 10000
  instanceDataBatchSize: 5000
  syncJobDisabled: false