# to be used when building in Jenkins
FROM harness/ubi:safe-ubi8.5

# Add the capsule JAR and config.yml
COPY --chown=65534:65534 cv-nextgen-capsule.jar /opt/harness/
COPY --chown=65534:65534 keystore.jks /opt/harness/
COPY --chown=65534:65534 cv-nextgen-config.yml /opt/harness/
COPY --chown=65534:65534 redisson-jcache.yaml /opt/harness/
COPY --chown=65534:65534 scripts /opt/harness/

RUN chmod 500 /opt/harness/*.sh

CMD [ "./run.sh" ]